FROM golang:1.24.4-alpine3.21 AS builder

WORKDIR /app

COPY . .

# Change to server directory where go.mod is located
WORKDIR /app/client

RUN CGO_ENABLED=0 GOOS=linux go build -o /api ./cmd

FROM alpine:latest

WORKDIR /

COPY --from=builder /api /api

EXPOSE 9000

CMD [ "/api" ]